-- liquibase formatted sql

-- changeset gusainovt:1
create table postal_office (
    id bigint generated by default as identity primary key,
    index varchar(10) not null,
    name varchar(255) not null,
    address varchar(255) not null
);

-- changeset gusainovt:2
create table postal_item (
    id bigint generated by default as identity primary key,
    recipient_name varchar(255) not null,
    type varchar(20) not null,
    recipient_index varchar(10) not null,
    recipient_address varchar(255) not null
);

-- changeset gusainovt:3
create table status (
   id bigint generated by default as identity primary key,
   arrival_time timestamp not null,
   postal_status varchar(20) not null,
   postal_office_id bigint,
   postal_item_id bigint,
   foreign key (postal_office_id) references postal_office(id),
   foreign key (postal_item_id) references postal_item(id)
);

-- changeset gusainovt:4
create table postal_item_movement_history (
    postal_item_id bigint,
    movement_history_id bigint,
    foreign key (postal_item_id) references postal_item(id),
    foreign key (movement_history_id) references status(id),
    primary key (postal_item_id, movement_history_id)
);